index:
    path: /
    controller: App\Controller\HomepageController::index

legal:
    path: /legal
    controller: App\Controller\HomepageController::legal

api:
    path : /api
    controller: App\Controller\VueApiController::index
